name: Render Remotion Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxrandr2 libgbm1 libxtst6 libpango-1.0-0 libcairo2 libgdk-pixbuf2.0-0
      
      - name: Render Video
        run: pnpm exec remotion render remotion/chart/BarRace.tsx out/video.mp4 --config src/remotion.config.ts

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Compress Video
        run: |
          mkdir -p compressed
          ffmpeg -i out/video.mp4 -vcodec libx265 -crf 28 compressed/video-compressed.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
          retention-days: 7
